# Generated by Django 4.1 on 2022-08-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("eat", "eat"),
                            ("toilet", "toilet"),
                            ("home", "home"),
                            ("care", "care"),
                        ],
                        default="eat",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="no_imgage.png", upload_to="product_images"
                    ),
                ),
            ],
        ),
    ]
