# Generated by Django 4.1 on 2022-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="group",
            field=models.CharField(
                choices=[
                    ("else", "else"),
                    ("home", "home"),
                    ("toilet", "toilet"),
                    ("eat", "eat"),
                    ("care", "care"),
                ],
                default="eat",
                max_length=10,
            ),
        ),
    ]
