# Generated by Django 4.1 on 2022-08-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_shop", "0002_alter_products_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="group",
            field=models.CharField(
                choices=[
                    ("Домик", "Домик"),
                    ("Наполнитель", "Наполнитель"),
                    ("Угощение", "Угощение"),
                    ("Лежанка", "Лежанка"),
                    ("Лоток", "Лоток"),
                    ("Другое", "Другое"),
                    ("Корм", "Корм"),
                    ("Средства по уходу", "Средства по уходу"),
                    ("Переноска", "Переноска"),
                ],
                default="Корм",
                max_length=50,
            ),
        ),
    ]
