# Generated by Django 4.1 on 2022-08-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_shop", "0003_alter_products_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="group",
            field=models.CharField(
                choices=[
                    ("Корм", "Корм"),
                    ("Лакомство", "Лакомство"),
                    ("Наполнитель", "Наполнитель"),
                    ("Домик", "Домик"),
                    ("Лоток", "Лоток"),
                    ("Другое", "Другое"),
                    ("Лежанка", "Лежанка"),
                    ("Средства по уходу", "Средства по уходу"),
                    ("Переноска", "Переноска"),
                ],
                default="Корм",
                max_length=50,
            ),
        ),
    ]
